import React from 'react';
import { PlayerValueCalculation } from '../../types';
import { Card } from '../shared/Card';
import { Tooltip } from '../shared/Tooltip';
import { useFormatting } from '../../hooks/useFormatting';

interface PlayerValueCalculatorProps {
  data: PlayerValueCalculation;
}

export function PlayerValueCalculator({ data }: PlayerValueCalculatorProps) {
  const { formatCurrency, formatNumber, formatPercent } = useFormatting();
  const newPlayerPercent = (data.newPlayers / data.incrementalInstalls) * 100;
  const reactivatedPercent = (data.reactivatedPlayers / data.incrementalInstalls) * 100;

  return (
    <Card title="Player Value Calculator" subtitle="ROI breakdown">
      <div className="space-y-4">
        {/* Total Installs - Big headline number */}
        <div className="bg-hay-cream rounded-lg p-4">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-2">
              <span className="text-sm font-semibold text-hay-brown uppercase tracking-wide">Total Installs</span>
              <Tooltip content="Total installs driven by campaign" />
            </div>
            <span className="text-2xl font-bold text-hay-gold font-display">
              {formatNumber(data.incrementalInstalls)}
            </span>
          </div>
          <div className="flex items-center gap-4 text-sm">
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-hay-green"></span>
              <span className="text-hay-brown-light">New</span>
              <span className="text-hay-brown font-medium">{newPlayerPercent.toFixed(0)}%</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-hay-gold"></span>
              <span className="text-hay-brown-light">Reactivated</span>
              <span className="text-hay-brown font-medium">{reactivatedPercent.toFixed(0)}%</span>
            </div>
          </div>
        </div>

        {/* Retained at D90 */}
        <div className="bg-hay-cream rounded-lg p-4">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-2">
              <span className="text-sm font-semibold text-hay-brown uppercase tracking-wide">Retained at D90</span>
              <Tooltip content="Players still active 90 days after install" />
            </div>
            <span className="text-2xl font-bold text-hay-green font-display">
              {formatNumber(data.retainedAtD90)}
            </span>
          </div>
          <div className="text-sm">
            <span className="text-hay-brown-light">Retention Rate: </span>
            <span className="text-hay-brown font-medium">{formatPercent(data.retentionRate)}</span>
          </div>
        </div>

        {/* Player Value */}
        <div className="bg-hay-cream rounded-lg p-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className="text-sm font-medium text-hay-brown">Player Value</span>
              <Tooltip content="Total revenue generated by retained players over 12 months" />
            </div>
            <span className="text-xl font-bold text-hay-gold font-display">
              {formatCurrency(data.playerValue)}
            </span>
          </div>
          <div className="mt-2 grid grid-cols-2 gap-2 text-sm">
            <div className="flex justify-between">
              <span className="text-hay-brown-light">ARPDAU</span>
              <span className="text-hay-brown">{formatCurrency(data.arpdau)}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-hay-brown-light">Avg Days</span>
              <span className="text-hay-brown">{data.avgDaysRetained}</span>
            </div>
          </div>
        </div>

        {/* Campaign ROI */}
        <div className="bg-hay-gold/20 rounded-lg p-4 border-2 border-hay-gold">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className="text-sm font-semibold text-hay-brown">Campaign ROI</span>
              <Tooltip content="Player value generated divided by campaign investment" />
            </div>
            <span className="text-2xl font-bold text-hay-gold font-display">
              {data.campaignROI.toFixed(2)}x
            </span>
          </div>
          <div className="mt-3 grid grid-cols-2 gap-2 text-sm">
            <div>
              <span className="text-hay-brown-light block">Value Generated</span>
              <span className="text-hay-brown font-semibold">{formatCurrency(data.valueGenerated)}</span>
            </div>
            <div>
              <span className="text-hay-brown-light block">Investment</span>
              <span className="text-hay-brown font-semibold">{formatCurrency(data.campaignInvestment)}</span>
            </div>
          </div>
        </div>
      </div>
    </Card>
  );
}
